import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { K2D } from "next/font/google";
import "../globals.css";
import { Toaster } from "@/components/ui/sonner"


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const k2dSans = K2D({
    weight: ['400', '700'],
    subsets: ["thai"],
});


export const metadata: Metadata = {
    title: "DashboardLayout",
    description: "Generated by create next app",
};

export default function Dashboard({
        children,
    }: Readonly<{
        children: React.ReactNode;  
    }>) {
    return (
        <html lang="en">

            <body
                className={`${k2dSans.className} antialiased`}
            >
                <h1>Header</h1>
                <hr></hr>
                {children}
                <Toaster />
            </body>
        </html>
    );
}
