import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Mitr, Charm } from "next/font/google";
import "../globals.css";
import { Toaster } from "@/components/ui/sonner"
import Navbar01Page from "@/components/navbar-01/navbar-01";
import Footer03Page from "@/components/footer-03/footer-03";
import AppQueryProvider from "../components/AppQueryProvider";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const mitrSans = Mitr({
  weight: ['400', '700'],
  subsets: ["thai"],
});

export const charmSans = Charm({
  weight: ['400', '700'],
  subsets: ["thai"],
});

export const metadata: Metadata = {
  title: "Create Next... App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > */}
      <body className={`${mitrSans.className} antialiased`}>

        <AppQueryProvider>
          <Navbar01Page />
          {children}
          <Toaster />
          <Footer03Page />
        </AppQueryProvider>
      </body>
    </html>
  );
}
